version: '3'
services:
  ghost:
    image: ghost:1-alpine
    ports: 
      - 2368:2368
    depends_on: 
      - database
  database:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 'blab'
      database__client: mysql
      database__connection__database: ghost
      database__connection__host: database
      database__connection__user: user
      database__connection__password: aa


